In [15]:
import torch
import torch.nn as nn

In [18]:
ln = nn.Linear(2, 4)
x = torch.tensor([[1., 2.], [3., 4.]])  # (batch_size, features)

In [42]:
z1_torch = ln(x)
z1_torch

tensor([[-1.3973,  1.7139, -0.6890, -0.5080],
        [-3.7889,  3.0700, -1.5421, -1.0503]], grad_fn=<AddmmBackward>)

In [43]:
W = ln.weight.data
W.requires_grad = True
W

tensor([[-0.5091, -0.6867],
        [-0.0095,  0.6875],
        [-0.5492,  0.1226],
        [-0.1947, -0.0765]], requires_grad=True)

In [33]:
b = ln.bias.data
b.requires_grad = True

tensor([ 0.4852,  0.3483, -0.3851, -0.1605])

In [34]:
torch.matmul(x, W.T) + b

tensor([[-1.3973,  1.7139, -0.6890, -0.5080],
        [-3.7889,  3.0700, -1.5421, -1.0503]])

In [37]:
z1

tensor([[-1.3973,  1.7139, -0.6890, -0.5080],
        [-3.7889,  3.0700, -1.5421, -1.0503]], grad_fn=<AddmmBackward>)

In [39]:
yhat = z1.mean()
yhat

tensor(-0.5240, grad_fn=<MeanBackward0>)

RuntimeError: can't retain_grad on Tensor that has requires_grad=False